# Generated by Django 6.0.2 on 2026-02-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('rating_category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgeRatingOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('rating_organization', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('company', models.CharField(max_length=255)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('language', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('mode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('platform', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('region', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SyncData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateField(auto_now=True)),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_rating', to='CDnutz_core.ageratingcategory')),
                ('age_rating_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_rating', to='CDnutz_core.ageratingorganization')),
            ],
            options={
                'unique_together': {('age_rating_org', 'age_rating_cat')},
            },
        ),
        migrations.CreateModel(
            name='GameAgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.agerating')),
            ],
        ),
        migrations.CreateModel(
            name='GameCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('developer', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.company')),
            ],
        ),
        migrations.CreateModel(
            name='GameLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('audio', models.BooleanField()),
                ('subtitle', models.BooleanField()),
                ('interface', models.BooleanField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.language')),
            ],
        ),
        migrations.CreateModel(
            name='GameRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('release_date', models.DateField(null=True)),
                ('date_precision', models.CharField(max_length=50, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.platform')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.region')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover', models.URLField(max_length=255, null=True)),
                ('summary', models.TextField(null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('age_ratings', models.ManyToManyField(related_name='games', through='CDnutz_core.GameAgeRating', to='CDnutz_core.agerating')),
                ('companies', models.ManyToManyField(related_name='games', through='CDnutz_core.GameCompany', to='CDnutz_core.company')),
                ('genres', models.ManyToManyField(related_name='games', to='CDnutz_core.genre')),
                ('languages', models.ManyToManyField(related_name='games', through='CDnutz_core.GameLanguage', to='CDnutz_core.language')),
                ('modes', models.ManyToManyField(related_name='games', to='CDnutz_core.mode')),
                ('platforms', models.ManyToManyField(related_name='games', through='CDnutz_core.GameRelease', to='CDnutz_core.platform')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='gamerelease',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.videogame'),
        ),
        migrations.AddField(
            model_name='gamelanguage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.videogame'),
        ),
        migrations.AddField(
            model_name='gamecompany',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.videogame'),
        ),
        migrations.AddField(
            model_name='gameagerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDnutz_core.videogame'),
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('media_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('artwork', 'Artwork')], max_length=50)),
                ('media_content', models.URLField(null=True)),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='CDnutz_core.videogame')),
            ],
            options={
                'unique_together': {('video_game', 'media_content')},
            },
        ),
    ]
