# Generated by Django 6.0.2 on 2026-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediacontent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='igdb_id',
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='mediacontent',
            constraint=models.UniqueConstraint(fields=('igdb_id', 'media_type'), name='unique_media_per_type'),
        ),
    ]
