# Generated by Django 6.0.2 on 2026-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0002_alter_mediacontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageratingcategory',
            name='rating_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ageratingorganization',
            name='rating_organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('artwork', 'Artwork')], max_length=255),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='servicekeys',
            name='service',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
