# Generated by Django 6.0.2 on 2026-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0003_alter_ageratingcategory_rating_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamerelease',
            name='date_precision',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
