# Generated by Django 6.0.2 on 2026-03-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0004_alter_company_website_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agerating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='agerating',
            constraint=models.UniqueConstraint(fields=('age_rating_org', 'age_rating_cat'), name='unique_agerating_pair'),
        ),
    ]
