# Generated by Django 6.0.2 on 2026-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0005_alter_agerating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncdata',
            options={},
        ),
        migrations.AlterField(
            model_name='syncdata',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
