# Generated by Django 6.0.2 on 2026-03-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0006_alter_syncdata_options_alter_syncdata_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('popularity_type', models.IntegerField(choices=[(6, 'Steam reviews'), (5, 'Steam peak players'), (2, 'IGDB wants')])),
                ('value', models.DecimalField(decimal_places=14, max_digits=16)),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='CDnutz_core.videogame')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('video_game', 'popularity_type'), name='unique_popularity_type_per_game')],
            },
        ),
    ]
