# Generated by Django 6.0.2 on 2026-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0007_popularityscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdata',
            name='data',
            field=models.CharField(choices=[('games', 'Games'), ('popscores', 'PopScores')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
