# Generated by Django 6.0.2 on 2026-03-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0008_syncdata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='videogame',
            name='bundle',
            field=models.ManyToManyField(related_name='bundled_in', to='CDnutz_core.videogame'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='game_type',
            field=models.CharField(choices=[(0, 'Main Game'), (1, 'DLC Addon'), (2, 'Expansion'), (3, 'Bundle'), (4, 'Standalone Expansion'), (5, 'Mod'), (6, 'Episode'), (7, 'Season'), (8, 'Remake'), (9, 'Remaster'), (10, 'Expanded Game'), (11, 'Port'), (12, 'Fork'), (13, 'Pack'), (14, 'Update')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogame',
            name='parent_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='CDnutz_core.videogame'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogame',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='CDnutz_core.franchise'),
        ),
    ]
