# Generated by Django 6.0.2 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0009_franchise_videogame_bundle_videogame_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
