# Generated by Django 6.0.2 on 2026-03-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0010_alter_videogame_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ageratingcategory',
            old_name='rating_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ageratingorganization',
            old_name='rating_organization',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mode',
            old_name='mode',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='platform',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
    ]
