# Generated by Django 6.0.2 on 2026-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0011_rename_rating_category_ageratingcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerating',
            name='cover',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='media_content',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='cover',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
