# Generated by Django 6.0.2 on 2026-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0012_agerating_cover_alter_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='animated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='artwork_type',
            field=models.CharField(choices=[(1, 'Artwork'), (2, 'Key art without logo'), (3, 'Key art with logo'), (4, 'Concept art'), (5, 'Game logo (white)'), (6, 'Game logo (black)'), (7, 'Game logo (color)'), (8, 'Infographic'), (9, 'Alternative cover'), (10, 'Historical cover')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('artwork', 'Artwork'), ('video', 'Video')], max_length=255),
        ),
    ]
