# Generated by Django 6.0.2 on 2026-03-31 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0013_mediacontent_animated_mediacontent_artwork_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameagerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_age_ratings', to='CDnutz_core.videogame'),
        ),
        migrations.AlterField(
            model_name='gamecompany',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_companies', to='CDnutz_core.videogame'),
        ),
        migrations.AlterField(
            model_name='gamelanguage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_languages', to='CDnutz_core.videogame'),
        ),
        migrations.AlterField(
            model_name='gamerelease',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_releases', to='CDnutz_core.videogame'),
        ),
        migrations.AlterField(
            model_name='popularityscore',
            name='video_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_popularity', to='CDnutz_core.videogame'),
        ),
    ]
