# Generated by Django 6.0.5 on 2026-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0016_alter_mediacontent_artwork_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='hype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videogame',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
