# Generated by Django 6.0.5 on 2026-06-29 06:55

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('CDnutz_core', '0017_videogame_hype_videogame_rating_count'),
    ]

    operations = [
        TrigramExtension()
    ]
